version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8000:80"
    depends_on:
      - "mssql-server"
    volumes:
      - /app/Dependencies
  mssql-server:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"